// frontend_vue/src/App.vue
<template>
  <v-app>
    <v-app-bar app color="primary" dark>
      <v-app-bar-nav-icon>
        <v-icon>mdi-account-multiple</v-icon>
      </v-app-bar-nav-icon>
      <v-toolbar-title>Sistema de Usuarios</v-toolbar-title>
    </v-app-bar>

    <v-main>
      <v-container class="py-6">
        <v-tabs v-model="tab" grow>
          <v-tab value="rest">
            <v-icon left>mdi-api</v-icon>
            REST
          </v-tab>
          <v-tab value="soap">
            <v-icon left>mdi-xml</v-icon>
            SOAP
          </v-tab>
        </v-tabs>

        <v-window v-model="tab">
          <v-window-item value="rest">
            <UserManagement
              :users="users"
              :loading="loading"
              @add-user="addUserRest"
            />
          </v-window-item>

          <v-window-item value="soap">
            <UserManagement
              :users="users"
              :loading="loading"
              @add-user="addUserSoap"
            />
          </v-window-item>
        </v-window>
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import axios from 'axios'
import UserManagement from '@/components/UserManagement.vue'

interface User {
  id: number
  name: string
  email: string
}

const tab = ref('rest')
const users = ref<User[]>([])
const loading = ref(false)

// Fetch inicial de usuarios
const fetchUsers = async () => {
  try {
    loading.value = true
    const response = await axios.get('http://localhost:3000/api/users')
    users.value = response.data
  } catch (error) {
    console.error('Error fetching users:', error)
  } finally {
    loading.value = false
  }
}

// Agregar usuario via REST
const addUserRest = async (userData: { name: string; email: string }) => {
  try {
    loading.value = true
    const response = await axios.post('http://localhost:3000/api/users', userData)
    users.value = [...users.value, response.data]
  } catch (error) {
    console.error('Error adding user:', error)
  } finally {
    loading.value = false
  }
}

// Agregar usuario via SOAP
const addUserSoap = async (userData: { name: string; email: string }) => {
  try {
    loading.value = true
    const response = await axios.post(
      'http://localhost:3000/soap',
      `<?xml version="1.0" encoding="UTF-8"?>
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
                        xmlns:user="http://example.com/user-service">
        <soapenv:Header/>
        <soapenv:Body>
          <user:createUserRequest>
            <user:name>${userData.name}</user:name>
            <user:email>${userData.email}</user:email>
          </user:createUserRequest>
        </soapenv:Body>
      </soapenv:Envelope>`,
      {
        headers: {
          'Content-Type': 'text/xml'
        }
      }
    )
    
    // Parsear respuesta SOAP y actualizar lista
    const parser = new DOMParser()
    const xmlDoc = parser.parseFromString(response.data, "text/xml")
    const newUser = {
      id: parseInt(xmlDoc.getElementsByTagName("id")[0].textContent || '0'),
      name: xmlDoc.getElementsByTagName("name")[0].textContent || '',
      email: xmlDoc.getElementsByTagName("email")[0].textContent || ''
    }
    users.value = [...users.value, newUser]
  } catch (error) {
    console.error('Error adding user via SOAP:', error)
  } finally {
    loading.value = false
  }
}

// Cargar usuarios cuando cambia la pestaña
watch(tab, (newTab) => {
  if (newTab === 'rest') {
    fetchUsers()
  } else {
    fetchUsers()
  }
}, { immediate: true })
</script>

<style scoped>
.v-tab {
  font-weight: 500;
}
</style>

// frontend_react/src/App.js
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Container,
  Typography,
  List,
  ListItem,
  ListItemText,
  TextField,
  Button,
  AppBar,
  Toolbar,
  Tabs,
  Tab,
  Box
} from '@mui/material';

function App() {
  const [users, setUsers] = useState([]);
  const [newUser, setNewUser] = useState({ name: '', email: '' });
  const [tabValue, setTabValue] = useState(0);

  // Cargar usuarios al iniciar
  useEffect(() => {
    fetchUsers();
  }, []);

  // Obtener usuarios via REST
  const fetchUsers = async () => {
    try {
      const response = await axios.get('http://localhost:3000/api/users');
      setUsers(response.data);
    } catch (error) {
      console.error('Error fetching users:', error);
    }
  };

  // Obtener usuarios via SOAP
  const fetchUsersSOAP = async () => {
    try {
      const response = await axios.post('http://localhost:3000/soap/service', 
        `<?xml version="1.0" encoding="UTF-8"?>
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
                          xmlns:user="http://example.com/user-service">
          <soapenv:Header/>
          <soapenv:Body>
            <user:getUsersRequest/>
          </soapenv:Body>
        </soapenv:Envelope>`,
        {
          headers: {
            'Content-Type': 'text/xml'
          }
        }
      );
      
      // Parsear respuesta XML
      const parser = new DOMParser();
      const xmlDoc = parser.parseFromString(response.data, "text/xml");
      const users = Array.from(xmlDoc.getElementsByTagName("user")).map(user => ({
        id: user.getElementsByTagName("id")[0].textContent,
        name: user.getElementsByTagName("name")[0].textContent,
        email: user.getElementsByTagName("email")[0].textContent
      }));
      
      setUsers(users);
    } catch (error) {
      console.error('Error fetching users via SOAP:', error);
    }
  };

  // Crear usuario via REST
  const createUser = async () => {
    try {
      await axios.post('http://localhost:3000/api/users', newUser);
      setNewUser({ name: '', email: '' });
      fetchUsers();
    } catch (error) {
      console.error('Error creating user:', error);
    }
  };

  // Crear usuario via SOAP
  const createUserSOAP = async () => {
    try {
      await axios.post('http://localhost:3000/soap/service', 
        `<?xml version="1.0" encoding="UTF-8"?>
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
                          xmlns:user="http://example.com/user-service">
          <soapenv:Header/>
          <soapenv:Body>
            <user:createUserRequest>
              <user:name>${newUser.name}</user:name>
              <user:email>${newUser.email}</user:email>
            </user:createUserRequest>
          </soapenv:Body>
        </soapenv:Envelope>`,
        {
          headers: {
            'Content-Type': 'text/xml'
          }
        }
      );
      
      setNewUser({ name: '', email: '' });
      fetchUsersSOAP();
    } catch (error) {
      console.error('Error creating user via SOAP:', error);
    }
  };

  const handleTabChange = (event, newValue) => {
    setTabValue(newValue);
    if (newValue === 0) fetchUsers();
    else fetchUsersSOAP();
  };

  return (
    <div>
      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Gestión de Usuarios
          </Typography>
        </Toolbar>
      </AppBar>
      
      <Container maxWidth="md" sx={{ mt: 4 }}>
        <Tabs value={tabValue} onChange={handleTabChange} aria-label="API tabs" centered>
          <Tab label="REST API" />
          <Tab label="SOAP API" />
        </Tabs>
        
        <Box sx={{ p: 3, border: 1, borderColor: 'divider', borderRadius: 1, mt: 2 }}>
          <Typography variant="h5" gutterBottom>
            {tabValue === 0 ? 'Usuarios (REST)' : 'Usuarios (SOAP)'}
          </Typography>
          
          <List>
            {users.map(user => (
              <ListItem key={user.id} sx={{ borderBottom: 1, borderColor: 'grey.200' }}>
                <ListItemText 
                  primary={user.name} 
                  secondary={`ID: ${user.id} - Email: ${user.email}`} 
                />
              </ListItem>
            ))}
          </List>
          
          <Typography variant="h6" gutterBottom sx={{ mt: 4 }}>
            Agregar Nuevo Usuario
          </Typography>
          
          <Box component="form" sx={{ mb: 3 }}>
            <TextField
              label="Nombre"
              value={newUser.name}
              onChange={(e) => setNewUser({...newUser, name: e.target.value})}
              fullWidth
              margin="normal"
              variant="outlined"
            />
            
            <TextField
              label="Email"
              value={newUser.email}
              onChange={(e) => setNewUser({...newUser, email: e.target.value})}
              fullWidth
              margin="normal"
              variant="outlined"
            />
            
            <Button 
              variant="contained" 
              onClick={tabValue === 0 ? createUser : createUserSOAP}
              sx={{ mt: 2 }}
            >
              Agregar Usuario
            </Button>
          </Box>
        </Box>
      </Container>
    </div>
  );
}

export default App;
